FROM python:3.9-slim

ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY pyproject.toml poetry.lock ./
RUN pip install --no-cache-dir poetry && \
    poetry install --no-root --no-dev

COPY . .

CMD ["python", "lambda_handler.py"]